# Generated by Django 6.0.3 on 2026-03-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрен'),
        ),
    ]
