# Generated by Django 6.0.3 on 2026-04-01 13:58

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название документа')),
                ('doc_type', models.CharField(choices=[('manual', 'Инструкция по эксплуатации'), ('passport', 'Паспорт изделия'), ('scheme', 'Электрическая схема'), ('certificate', 'Сертификат'), ('datasheet', 'Технический паспорт'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to=app.models.document_upload_path, verbose_name='Файл')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Документ товара',
                'verbose_name_plural': 'Документы товаров',
                'ordering': ['order', 'doc_type', 'title'],
            },
        ),
    ]
